# Generated by Django 2.2.6 on 2019-10-09 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otp_email', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuthEmailDevice',
            fields=[
                ('emaildevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='otp_email.EmailDevice')),
                ('attempts', models.SmallIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_requested', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('otp_email.emaildevice', models.Model),
        ),
    ]
